// Certification library — pre-loaded data for onboarding and Supabase seeding
export const CERTIFICATIONS = [
  {
    id: 'cpa',
    name: 'CPA (Certified Public Accountant)',
    short: 'CPA',
    category: 'Accounting',
    totalHours: 370,
    icon: '📊',
    color: '#6366f1',
    sections: [
      { name: 'FAR', fullName: 'Financial Accounting & Reporting', recommendedHours: 150, order: 1 },
      { name: 'AUD', fullName: 'Auditing & Attestation', recommendedHours: 80, order: 2 },
      { name: 'REG', fullName: 'Regulation', recommendedHours: 80, order: 3 },
      { name: 'BEC', fullName: 'Business Environment & Concepts', recommendedHours: 60, order: 4 },
    ],
  },
  {
    id: 'cfa1',
    name: 'CFA Level 1',
    short: 'CFA L1',
    category: 'Finance',
    totalHours: 290,
    icon: '📈',
    color: '#10b981',
    sections: [
      { name: 'Ethics', fullName: 'Ethical & Professional Standards', recommendedHours: 40, order: 1 },
      { name: 'Quant', fullName: 'Quantitative Methods', recommendedHours: 30, order: 2 },
      { name: 'Econ', fullName: 'Economics', recommendedHours: 30, order: 3 },
      { name: 'FRA', fullName: 'Financial Reporting & Analysis', recommendedHours: 50, order: 4 },
      { name: 'Corp Fin', fullName: 'Corporate Finance', recommendedHours: 25, order: 5 },
      { name: 'Equity', fullName: 'Equity Investments', recommendedHours: 30, order: 6 },
      { name: 'Fixed Inc', fullName: 'Fixed Income', recommendedHours: 30, order: 7 },
      { name: 'Derivatives', fullName: 'Derivatives', recommendedHours: 20, order: 8 },
      { name: 'Alt Inv', fullName: 'Alternative Investments', recommendedHours: 15, order: 9 },
      { name: 'Portfolio', fullName: 'Portfolio Management', recommendedHours: 20, order: 10 },
    ],
  },
  {
    id: 'pmp',
    name: 'PMP (Project Management Professional)',
    short: 'PMP',
    category: 'Management',
    totalHours: 200,
    icon: '🗂️',
    color: '#f59e0b',
    sections: [
      { name: 'Predictive', fullName: 'Predictive Project Management', recommendedHours: 80, order: 1 },
      { name: 'Agile', fullName: 'Agile Project Management', recommendedHours: 80, order: 2 },
      { name: 'Hybrid', fullName: 'Hybrid Approaches', recommendedHours: 40, order: 3 },
    ],
  },
  {
    id: 'bar',
    name: 'Bar Exam',
    short: 'Bar',
    category: 'Law',
    totalHours: 210,
    icon: '⚖️',
    color: '#ef4444',
    sections: [
      { name: 'MBE', fullName: 'Multistate Bar Examination', recommendedHours: 120, order: 1 },
      { name: 'MEE', fullName: 'Multistate Essay Examination', recommendedHours: 60, order: 2 },
      { name: 'MPT', fullName: 'Multistate Performance Test', recommendedHours: 30, order: 3 },
    ],
  },
  {
    id: 'aws-sa',
    name: 'AWS Solutions Architect Associate',
    short: 'AWS SAA',
    category: 'Technology',
    totalHours: 100,
    icon: '☁️',
    color: '#f97316',
    sections: [
      { name: 'Cloud Concepts', fullName: 'Cloud Concepts & AWS Global Infra', recommendedHours: 20, order: 1 },
      { name: 'Security', fullName: 'Security, Identity & Compliance', recommendedHours: 30, order: 2 },
      { name: 'Technology', fullName: 'AWS Technology & Services', recommendedHours: 40, order: 3 },
      { name: 'Billing', fullName: 'Billing, Pricing & Support', recommendedHours: 10, order: 4 },
    ],
  },
  {
    id: 'series7',
    name: 'Series 7 (General Securities Representative)',
    short: 'Series 7',
    category: 'Finance',
    totalHours: 150,
    icon: '💹',
    color: '#8b5cf6',
    sections: [
      { name: 'Equities', fullName: 'Equity Securities', recommendedHours: 40, order: 1 },
      { name: 'Debt', fullName: 'Debt Securities', recommendedHours: 35, order: 2 },
      { name: 'Options', fullName: 'Options Strategies', recommendedHours: 35, order: 3 },
      { name: 'Regulations', fullName: 'Regulations & Customer Accounts', recommendedHours: 40, order: 4 },
    ],
  },
  {
    id: 'comptia-sec',
    name: 'CompTIA Security+',
    short: 'Security+',
    category: 'Technology',
    totalHours: 120,
    icon: '🔒',
    color: '#e11d48',
    sections: [
      { name: 'Threats', fullName: 'Threats, Attacks and Vulnerabilities', recommendedHours: 25, order: 1 },
      { name: 'Architecture', fullName: 'Architecture and Design', recommendedHours: 20, order: 2 },
      { name: 'Implementation', fullName: 'Implementation', recommendedHours: 25, order: 3 },
      { name: 'Operations', fullName: 'Operations and Incident Response', recommendedHours: 20, order: 4 },
      { name: 'Governance', fullName: 'Governance, Risk and Compliance', recommendedHours: 30, order: 5 },
    ],
  },
  {
    id: 'cisa',
    name: 'CISA (Certified Information Systems Auditor)',
    short: 'CISA',
    category: 'Technology',
    totalHours: 350,
    icon: '🛡️',
    color: '#0ea5e9',
    sections: [
      { name: 'Domain 1', fullName: 'Information System Auditing Process', recommendedHours: 130, order: 1 },
      { name: 'Domain 2', fullName: 'Governance and Management of IT', recommendedHours: 50, order: 2 },
      { name: 'Domain 3', fullName: 'IS Acquisition, Development and Implementation', recommendedHours: 50, order: 3 },
      { name: 'Domain 4', fullName: 'IS Operations and Business Resilience', recommendedHours: 50, order: 4 },
      { name: 'Domain 5', fullName: 'Protection of Information Assets', recommendedHours: 70, order: 5 },
    ],
  },
  {
    id: 'usmle1',
    name: 'USMLE Step 1',
    short: 'USMLE 1',
    category: 'Medicine',
    totalHours: 500,
    icon: '🏥',
    color: '#06b6d4',
    sections: [
      { name: 'Anatomy', fullName: 'Gross Anatomy & Embryology', recommendedHours: 80, order: 1 },
      { name: 'Biochem', fullName: 'Biochemistry & Genetics', recommendedHours: 90, order: 2 },
      { name: 'Physiology', fullName: 'Physiology', recommendedHours: 100, order: 3 },
      { name: 'Pathology', fullName: 'Pathology', recommendedHours: 120, order: 4 },
      { name: 'Pharmacology', fullName: 'Pharmacology', recommendedHours: 70, order: 5 },
      { name: 'Micro/Immuno', fullName: 'Microbiology & Immunology', recommendedHours: 40, order: 6 },
    ],
  },
]

export const getCertById = (id) => CERTIFICATIONS.find((c) => c.id === id)

export const SECTION_COLORS = [
  '#6366f1', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6',
  '#06b6d4', '#f97316', '#ec4899', '#14b8a6', '#a855f7',
]
